name: medicord
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  sqflite: ^2.4.1
  json_annotation: ^4.9.0
  path: ^1.9.0
  provider: ^6.1.2
  intl: ^0.19.0
  fl_chart: ^0.69.2
  table_calendar: ^3.1.2
  collection: ^1.18.0
  go_router: ^14.6.2

dev_dependencies:
  sqflite_common_ffi: ^2.3.4
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
